### PR TITLE
Migrate to m114

### PR DESCRIPTION
**Pull request by hiroshihorie**
Checking if audio changes still work correctly:
[@cloudwebrtc ](https://github.com/webrtc-sdk/webrtc/pull/76#issuecomment-1617696893)

### CODE REVIEW

**Comment by cloudwebrtc** [comment]
It works correctly, except that you need to change RTCAudioDevice to RTCIODevice in macOS
https://github.com/livekit-examples/swift-example/pull/17

**Comment by davidzhao** [comment]
> It works correctly, just need to change `RTCAudioDevice` to `RTCIODevice` in swift-example [livekit-examples/swift-example#17](https://github.com/livekit-examples/swift-example/pull/17)

Is this an breaking API change?

**Comment by cloudwebrtc** [comment]
Yes, RTCAudioDevice has a naming conflict with `RTCAudioDevice` added in m114.

In our https://github.com/webrtc-sdk/webrtc/pull/21 patch, RTCAudioDevice refers to a specific sound card or usb hardware https://github.com/webrtc-sdk/webrtc/blob/m104_release/sdk/objc/api/peerconnection/RTCAudioDevice.h#L25, 

and m114 refers to audio device module 
https://github.com/webrtc-sdk/webrtc/blob/m114_release/sdk/objc/components/audio/RTCAudioDevice.h#L167

**Comment by cloudwebrtc** [comment]
https://github.com/webrtc-sdk/Specs/releases/tag/114.5735.02

**Review by davidzhao — APPROVED** [review]

**Pull request merged**
