### PR TITLE
Support visionOS Front/Persona Camera

### PR DESCRIPTION
**Pull request by gching**
Ref: https://livekit-users.slack.com/archives/C07FVFGAUKX/p1723112131622469

## Changes 
* **Still not working as expected**
* visionOS does not support `DiscoverySession` or `.default` to find the front / persona camera device, but supports `.systemPreferredCamera` which returns only one device which is the front / persona camera
* Added some logic to return the device in `DeviceManager`
* Using https://github.com/livekit-examples/swift-example, querying for the device works as expected, but starting the video stream timeouts on waiting for the dimensions to resolve https://github.com/livekit/client-sdk-swift/blob/eaf1e24aaa31b24cb207d37992a9075c3ed0ca49/Sources/LiveKit/Participant/LocalParticipant.swift#L481

## Miscellaneous
* Xcode 16 beta 4
* visionOS 2 beta 5

### CODE REVIEW

**Comment by hiroshihorie** [comment]
Thanks for looking into this, do you see :
"starting camera capturer device" in the logs ?

**Comment by gching** [comment]
Yep! Seeing the following:

```
2024-08-09T03:12:34-0700 info LiveKitSDK : [LiveKit] CameraCapturer.startCapture() starting camera capturer device: <AVCaptureFigVideoDevice: 0x109034e00 [Front Camera][com.apple.avfoundation.avcapturedevice.built-in_video:1]>, format: (format: 'vide'/'420v' 1920x1080, { 1- 30 fps}, photo dims:{1920x1080,2112x1188}, supports vis (max strength:Low), max zoom:67.50 (upscales @1.00), supports multicam, dimensions: Dimensions(1920x1080)), fps: 30(0...30)
2024-08-09T03:12:34-0700 debug LiveKitSDK : [LiveKit] LocalParticipant._publish(track:options:) [Publish] Waiting for dimensions to resolve...
2024-08-09T03:12:34-0700 debug LiveKitSDK : [LiveKit] AsyncCompleter<Dimensions>.wait(timeout:) Dimensions waiting milliseconds(20000) with id: 95F1FA24-20EE-47F6-9FF7-5F622B5F4844
cannot add handler to 0 from 1 - dropping
2024-08-09T03:12:54-0700 debug LiveKitSDK : [LiveKit] AsyncCompleter<Dimensions>.wait(timeout:) Wait 95F1FA24-20EE-47F6-9FF7-5F622B5F4844 timedOut
2024-08-09T03:12:54-0700 error LiveKitSDK : [LiveKit] LocalParticipant._publish(track:options:) [publish] failed LocalVideoTrack(sid: nil, name: camera, source: Source(rawValue: 1)), error: Error Domain=io.livekit.swift-sdk Code=101 "Timed out" UserInfo={NSLocalizedDescription=Timed out}
2024-08-09T03:12:54-0700 debug LiveKitSDK : [LiveKit] CameraCapturer.init(delegate:) startStopCounter 1 -> 0
2024-08-09T03:12:54-0700 debug LiveKitSDK : [LiveKit] AsyncTimer.deinit 
```

Note - I changed the timeout to be `20000` milliseconds just to see if it changed anything, so don't worry about that in the above logs!

**Comment by hiroshihorie** [comment]
Thanks for your hints, I have another branch working on this. Will push in a few hours.

**Comment by bcherry** [comment]
@hiroshihorie I actually have the same exact problem in `main` on my iPhone 14 Pro so it's not visionOS-specific

**Comment by hiroshihorie** [comment]
I have it working on this [branch](https://github.com/livekit/client-sdk-swift/pull/460)
There was a mistake in for visionOS in WebRTC level so I patched it.

**Comment by gching** [comment]
Amazing Hiroshi! Tested #460 on my device and persona is working! Thank you for getting it working and patching WebRTC as well 🚀 

Closing this PR given #460

**Pull request closed without merging**
