### PR TITLE
DispatchQueue improvements

### PR DESCRIPTION
**Pull request by hiroshihorie**
Using common static .sdk queue was a bad idea, queue gets too congested when multiple Room/Engine objects.
Concurrent Room connecting works well now.

### CODE REVIEW

**Review by davidzhao — APPROVED** [review]
lg! should room/engine/signalclient each uses their own dispatch queue? should they share in some cases?

**Comment by hiroshihorie** [comment]
Good point, should be ok because all state is managed through the **state lock** regardless of the thread the promise executes on https://github.com/livekit/client-sdk-swift/blob/main/Sources/LiveKit/Support/StateSync.swift .
But I will double check and be more confident if I write more e2e tests.

**Comment by hiroshihorie** [comment]
Properties **not** protected by the `StateSync` https://github.com/livekit/client-sdk-swift/blob/main/Sources/LiveKit/Support/StateSync.swift should be safe as long as It is private (won't be accessed from another queue/thread).
I think 😅

**Comment by davidzhao** [comment]
> Properties **not** protected by the `StateSync` https://github.com/livekit/client-sdk-swift/blob/main/Sources/LiveKit/Support/StateSync.swift should be safe as long as It is private (won't be accessed from another queue/thread). I think 😅

got it, thanks!

**Pull request merged**
