### PR TITLE
Fix iOS unable to publish 1080p

### PR DESCRIPTION
**Pull request by hiroshihorie**
Rewrite profile level for iOS also

Fixes 
https://github.com/livekit/client-sdk-swift/issues/144

### CODE REVIEW

**Review by cloudwebrtc — APPROVED** [review]
lgtm

**Review by cnderrauber — APPROVED** [review]
LGTM! does `42e032` support by the very old model iphones

**Comment by hiroshihorie** [comment]
@cnderrauber good point... I'm not sure how to investigate this

**Comment by hiroshihorie** [comment]
@cnderrauber
Maybe it works since iOS8
https://developer.apple.com/documentation/videotoolbox/kvtprofilelevel_h264_baseline_5_0

**Pull request merged**
